"""add_recording_consent_to_patients

Revision ID: cafe245ac3d2
Revises: d157c7b7457c
Create Date: 2026-04-02 09:53:53.583852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cafe245ac3d2'
down_revision: Union[str, None] = 'd157c7b7457c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('recording_consent', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'recording_consent')
    # ### end Alembic commands ###
